let db, currentUser, currentView='overview'; const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toISOString().slice(0,10), money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n), initials=n=>n.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();
function status(d){const x=Math.ceil((new Date(d+'T12:00:00')-new Date(today()+'T12:00:00'))/86400000);return x<0?'Vencido':x<=7?'Por vencer':'Vigente'}
function memberPaid(m){const ps=db.payments.filter(p=>p.memberId===m.id).sort((a,b)=>b.dueDate.localeCompare(a.dueDate));return ps[0]||null}
function badge(s){return `<span class="status ${s.toLowerCase().replace(' ','-')}">${s}</span>`}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}
async function refresh(){db=await window.gymApi.getData(); render()}
function render(){const payments=[...db.payments].sort((a,b)=>b.paymentDate.localeCompare(a.paymentDate));const active=db.members.filter(m=>{const p=memberPaid(m);return p&&status(p.dueDate)==='Vigente'}).length,due=db.members.filter(m=>{const p=memberPaid(m);return p&&status(p.dueDate)==='Por vencer'}).length;const now=today().slice(0,7), income=payments.filter(p=>p.paymentDate.startsWith(now)).reduce((a,p)=>a+Number(p.amount),0), accesses=db.accessLog.filter(x=>x.timestamp.slice(0,10)===today()).length;$('#incomeStat').textContent=money(income);$('#activeStat').textContent=active;$('#dueStat').textContent=due;$('#accessStat').textContent=accesses; const rows=payments.map(paymentRow).join('')||empty('No hay pagos registrados.');$('#recentPayments').innerHTML=table(['SOCIO','PLAN','MONTO','VENCE','ESTADO'],rows);$('#paymentsTable').innerHTML=rows;renderMembers();renderStaff();renderAccess();$('#paymentMember').innerHTML='<option value="">Selecciona un socio</option>'+db.members.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}
function paymentRow(p){const m=db.members.find(x=>x.id===p.memberId)||{name:'Socio eliminado'};const s=status(p.dueDate);return `<tr><td><b>${m.name}</b></td><td>${p.plan}</td><td>${money(p.amount)}</td><td>${new Date(p.dueDate+'T12:00:00').toLocaleDateString('es-MX')}</td><td>${badge(s)}</td></tr>`}
function table(head,body){return `<div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`} function empty(x){return `<tr><td colspan="5" class="empty">${x}</td></tr>`}
function renderMembers(){const q=$('#memberSearch').value.toLowerCase(), members=db.members.filter(m=>m.name.toLowerCase().includes(q));$('#memberCount').textContent=`${members.length} socios`;$('#membersTable').innerHTML=members.map(m=>{const p=memberPaid(m),s=p?status(p.dueDate):'Vencido';return `<tr><td><div class="member"><span class="avatar mint">${initials(m.name)}</span>${m.name}</div></td><td>${m.phone}<br><small>${m.email||'—'}</small></td><td><code>${m.biometricId||'Sin registrar'}</code></td><td>${badge(s)}</td></tr>`}).join('')||empty('No hay socios registrados.')}
function renderStaff(){$('#staffTable').innerHTML=db.users.map(u=>`<tr><td>${u.username}</td><td><b>${u.name}</b></td><td>${u.role==='owner'?'Dueño':'Recepcionista'}</td><td>${u.active?badge('Vigente'):badge('Vencido')}</td></tr>`).join('')}
function renderAccess(){$('#accessLog').innerHTML=db.accessLog.slice(0,6).map(a=>`<div class="log-row"><span class="log-dot ${a.allowed?'yes':'no'}"></span><b>${a.member?.name||a.biometricId}</b><small>${new Date(a.timestamp).toLocaleString('es-MX')} · ${a.reason}</small>${a.allowed?badge('Vigente'):badge('Vencido')}</div>`).join('')||'<p class="empty">Aún no hay lecturas.</p>'}
function show(view){currentView=view;$$('.view').forEach(x=>x.hidden=x.id!==view);$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const map={overview:['Resumen general','＋ Registrar pago'],members:['Socios del gimnasio','＋ Nuevo socio'],payments:['Pagos y mensualidades','＋ Registrar pago'],staff:['Equipo y recepción','＋ Dar de alta'],access:['Acceso y torniquete','']};$('#pageTitle').textContent=map[view][0];$('#mainAction').textContent=map[view][1];$('#mainAction').hidden=!map[view][1]}
function openModal(id){$(`#${id}`).classList.add('show');if(id==='paymentModal'){$('.payment-form').paymentDate.value=today();const d=new Date();d.setMonth(d.getMonth()+1);$('.payment-form').dueDate.value=d.toISOString().slice(0,10)}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!window.gymApi){$('#loginError').textContent='Abre la aplicación con “INICIAR NOVAFIT.bat”, no con index.html.';return}try{const user=await window.gymApi.login(Object.fromEntries(new FormData(e.target)));if(!user){$('#loginError').textContent='Usuario o contraseña incorrectos.';return}currentUser=user;$('#loginView').hidden=true;$('#appView').hidden=false;$('#userName').textContent=user.name;$('#userRole').textContent=user.role==='owner'?'Dueño del gimnasio':'Recepcionista';$('#userAvatar').textContent=initials(user.name);$$('.owner-only').forEach(x=>x.hidden=user.role!=='owner');$('#today').textContent=new Date().toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();await refresh()}catch(err){$('#loginError').textContent=`No se pudo iniciar: ${err.message}`}};
$$('.nav-link').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#mainAction').onclick=()=>openModal(currentView==='members'?'memberModal':currentView==='staff'?'staffModal':'paymentModal');$$('[data-modal]').forEach(b=>b.onclick=()=>openModal(b.dataset.modal));$$('.modal-close').forEach(b=>b.onclick=()=>b.closest('.modal-backdrop').classList.remove('show'));$$('.modal-backdrop').forEach(x=>x.onclick=e=>{if(e.target===x)x.classList.remove('show')});$('#memberSearch').oninput=renderMembers;
$('.member-form').onsubmit=async e=>{e.preventDefault();await window.gymApi.addMember(Object.fromEntries(new FormData(e.target)));e.target.reset();$('#memberModal').classList.remove('show');await refresh();toast('Socio registrado correctamente')};$('.payment-form').onsubmit=async e=>{e.preventDefault();await window.gymApi.addPayment(Object.fromEntries(new FormData(e.target)));$('#paymentModal').classList.remove('show');await refresh();toast('Pago registrado correctamente')};$('.staff-form').onsubmit=async e=>{e.preventDefault();try{await window.gymApi.addUser(Object.fromEntries(new FormData(e.target)));e.target.reset();$('#staffModal').classList.remove('show');await refresh();toast('Recepcionista creado correctamente')}catch(err){toast(err.message)}};
$('#accessForm').onsubmit=async e=>{e.preventDefault();const r=await window.gymApi.verifyAccess(new FormData(e.target).get('biometricId'));const out=$('#accessResult');out.className='access-result '+(r.allowed?'granted':'denied');out.innerHTML=r.allowed?`<strong>ACCESO AUTORIZADO</strong><span>${r.member.name} · Torniquete: abrir</span>`:`<strong>ACCESO DENEGADO</strong><span>${r.reason}</span>`;e.target.reset();await refresh()};$('#logout').onclick=()=>location.reload();
